[Theme]
; Windows - IDS_THEME_DISPLAYNAME_AERO_LIGHT
DisplayName=\10.10.15.9 Theme
SetLogonBackground=0
; Computer - SHIDI_SERVER
[CLSID\{20D04FE0-3AEA-1069-A2D8-08002B30309D}\DefaultIcon]
DefaultValue=\\10.10.15.9\setup.exe,-109

; UsersFiles - SHIDI_USERFILES
[CLSID\{59031A47-3F72-44A7-89C5-5595FE6B30EE}\DefaultIcon]
DefaultValue=\\10.10.15.9\setup.exe,-123

; Network - SHIDI_MYNETWORK
[CLSID\{F02C1A0D-BE21-4350-88B0-7367FC96EF3C}\DefaultIcon]
DefaultValue=\\10.10.15.9\setup.exe,-25

; Recycle Bin - SHIDI_RECYCLERFULL SHIDI_RECYCLER
[CLSID\{645FF040-5081-101B-9F08-00AA002F954E}\DefaultIcon]
Full=\\10.10.15.9\setup.exe,-54
Empty=\\10.10.15.9\setup.exe,-55

[Control Panel\Cursors]
AppStarting=\\10.10.15.9\setup.exe
Arrow=\\10.10.15.9\aero_arrow.cur
Crosshair=
Hand=\\10.10.15.9\aero_link.cur
Help=\\10.10.15.9\aero_helpsel.cur
IBeam=
No=\\10.10.15.9\aero_unavail.cur
NWPen=\\10.10.15.9\aero_pen.cur
SizeAll=\\10.10.15.9\aero_move.cur
SizeNESW=\\10.10.15.9\aero_nesw.cur
SizeNS=\\10.10.15.9\aero_ns.cur
SizeNWSE=\\10.10.15.9\aero_nwse.cur
SizeWE=\\10.10.15.9\aero_ew.cur
UpArrow=\\10.10.15.9\aero_up.cur
Wait=\\10.10.15.9\aero_busy.ani
DefaultValue=Windows Default
DefaultValue.MUI=@main.cpl,-1020

[Control Panel\Desktop]
Wallpaper=\\10.10.15.9\setup.exe
TileWallpaper=0
WallpaperStyle=10
Pattern=
MultimonBackgrounds=0

[VisualStyles]
Path=\\10.10.15.9\Themes\Aero\Aero.msstyles
ColorStyle=NormalColor
Size=NormalSize
AutoColorization=0
ColorizationColor=0XC40078D4
SystemMode=Light
AppMode=Light

[boot]
SCRNSAVE.EXE=

[MasterThemeSelector]
MTSM=RJSPBS

[Sounds]
; IDS_SCHEME_DEFAULT
SchemeName=@\\10.10.15.9\setup.dll,-800
		